// Terraforming Mars content chunk set5: official base cards 143-176 (32 cards; [CE] ones get ce: true).
// Tests: packages/game-engine/test/terraforming-mars-set5.test.ts
import { hasTag, vpPerRes, type CardDef, type Ctx } from '../api.ts';

/** Own cards in play holding at least 1 resource of any type (CEO's Favorite Project). */
const cardsWithRes = (g: Ctx) => g.tableau().filter((id) => g.card(id).resource && g.resOn(id) >= 1);

export const set5: CardDef[] = [
  { id: '143', name: 'Large Convoy', nameFa: 'کاروان بزرگ', kind: 'event', cost: 36, tags: ['earth', 'space'], vp: 2,
    textFa: '۱ اقیانوس بگذارید و ۲ کارت بکشید. ۵ گیاه بگیرید یا ۴ جانور به کارتی دیگر بیفزایید.',
    oceans: 1, draw: 2,
    play: (g) => {
      if (g.cardsWith('animal', { other: true }).length) g.choose(['۵ گیاه', '۴ جانور به کارتی دیگر'], 'pick');
      else g.gain('plants', 5);
    },
    resolve: { pick: (g, a) => (a.index === 0 ? g.gain('plants', 5) : g.addToCard('animal', 4, true)) } },
  { id: '144', name: 'Titanium Mine', nameFa: 'معدن تیتانیوم', kind: 'automated', cost: 7, tags: ['building'], ce: true,
    textFa: '۱ تولید تیتانیوم.', prod: { titanium: 1 } },
  { id: '145', name: 'Tectonic Stress Power', nameFa: 'نیروی تنش زمین‌ساختی', kind: 'automated', cost: 18, tags: ['power', 'building'], vp: 1,
    req: { tags: { science: 2 } }, textFa: 'نیاز: ۲ نشان علم. ۳ تولید انرژی.', prod: { energy: 3 } },
  { id: '146', name: 'Nitrophilic Moss', nameFa: 'خزهٔ نیترات‌دوست', kind: 'automated', cost: 8, tags: ['plant'],
    req: { oceans: { min: 3 } }, textFa: 'نیاز: ۳ اقیانوس. ۲ گیاه از دست می‌دهید؛ ۲ تولید گیاه.', gain: { plants: -2 }, prod: { plants: 2 } },
  { id: '147', name: 'Herbivores', nameFa: 'گیاه‌خواران', kind: 'active', cost: 12, tags: ['animal'], resource: 'animal',
    req: { oxygen: { min: 8 } }, vp: vpPerRes(2),
    textFa: 'نیاز: ۸٪ اکسیژن. ۱ جانور به این کارت؛ ۱− تولید گیاه یک بازیکن. هر بار فضای سبز بگذارید ۱ جانور به این کارت. ۱ امتیاز برای هر ۲ جانور.',
    addSelf: 1, anyProd: { res: 'plants', n: 1 },
    onTilePlaced: (g, e) => { if (e.seat === g.seat && e.kind === 'greenery') g.addRes(1); } },
  { id: '148', name: 'Insects', nameFa: 'حشرات', kind: 'automated', cost: 9, tags: ['microbe'], req: { oxygen: { min: 6 } },
    textFa: 'نیاز: ۶٪ اکسیژن. ۱ تولید گیاه برای هر نشان گیاه که دارید.', prodBox: (g) => g.prod('plants', g.tags('plant')) },
  { id: '149', name: "CEO's Favorite Project", nameFa: 'پروژهٔ محبوب مدیرعامل', kind: 'event', cost: 1, tags: [], ce: true,
    textFa: '۱ منبع به یکی از کارت‌هایتان که دست‌کم ۱ منبع دارد بیفزایید.',
    canPlay: (g) => cardsWithRes(g).length > 0,
    play: (g) => g.prompt({ kind: 'card', options: cardsWithRes(g), then: { card: '149', key: 'add' }, labelFa: 'کارتی که ۱ منبع می‌گیرد' }),
    resolve: { add: (g, a) => g.addRes(1, a.card) } },
  { id: '150', name: 'Anti-Gravity Technology', nameFa: 'فناوری ضدجاذبه', kind: 'active', cost: 14, tags: ['science'], ce: true, vp: 3,
    req: { tags: { science: 7 } }, textFa: 'نیاز: ۷ نشان علم. همهٔ کارت‌هایی که بازی می‌کنید ۲ مگاکردیت ارزان‌تر.', discount: () => 2 },
  { id: '151', name: 'Investment Loan', nameFa: 'وام سرمایه‌گذاری', kind: 'event', cost: 3, tags: ['earth'], ce: true,
    textFa: '۱− تولید مگاکردیت؛ ۱۰ مگاکردیت بگیرید.', prod: { mc: -1 }, gain: { mc: 10 } },
  { id: '154', name: 'Caretaker Contract', nameFa: 'قرارداد سرپرستی', kind: 'active', cost: 3, tags: [], ce: true,
    req: { temperature: { min: 0 } }, textFa: 'نیاز: دمای ۰ یا گرم‌تر. کنش: ۸ گرما خرج کنید و ۱ رتبهٔ زمین‌سازی بگیرید.',
    action: { can: (g) => g.p.res.heat >= 8, run: (g) => { g.gain('heat', -8); g.tr(1); } } },
  { id: '155', name: 'Designed Microorganisms', nameFa: 'ریزجانداران طراحی‌شده', kind: 'automated', cost: 16, tags: ['science', 'microbe'],
    req: { temperature: { max: -14 } }, textFa: 'نیاز: دمای ۱۴− یا سردتر. ۲ تولید گیاه.', prod: { plants: 2 } },
  { id: '156', name: 'Standard Technology', nameFa: 'فناوری استاندارد', kind: 'active', cost: 6, tags: ['science'], ce: true,
    textFa: 'پس از پرداخت هزینهٔ هر پروژهٔ استاندارد جز فروش امتیاز اختراع، ۳ مگاکردیت بگیرید.',
    onStandardProject: (g, e) => { if (e.seat === g.seat && e.project !== 'sellPatents') g.gain('mc', 3); } },
  { id: '157', name: 'Nitrite Reducing Bacteria', nameFa: 'باکتری‌های کاهندهٔ نیتریت', kind: 'active', cost: 11, tags: ['microbe'], resource: 'microbe',
    textFa: '۳ میکروب به این کارت. کنش: ۱ میکروب به این کارت، یا ۳ میکروب از آن بردارید و ۱ رتبهٔ زمین‌سازی بگیرید.',
    addSelf: 3,
    action: { run: (g) => (g.resOn() >= 3 ? g.choose(['۱ میکروب به این کارت', '۳ میکروب بردارید: ۱ رتبهٔ زمین‌سازی'], 'act') : g.addRes(1)) },
    resolve: { act: (g, a) => { if (a.index === 0) g.addRes(1); else { g.addRes(-3); g.tr(1); } } } },
  { id: '158', name: 'Industrial Microbes', nameFa: 'میکروب‌های صنعتی', kind: 'automated', cost: 12, tags: ['microbe', 'building'],
    textFa: '۱ تولید انرژی و ۱ تولید فولاد.', prod: { energy: 1, steel: 1 } },
  { id: '159', name: 'Lichen', nameFa: 'گلسنگ', kind: 'automated', cost: 7, tags: ['plant'], req: { temperature: { min: -24 } },
    textFa: 'نیاز: دمای ۲۴− یا گرم‌تر. ۱ تولید گیاه.', prod: { plants: 1 } },
  { id: '160', name: 'Power Supply Consortium', nameFa: 'کنسرسیوم تأمین برق', kind: 'automated', cost: 5, tags: ['power'], ce: true,
    req: { tags: { power: 2 } }, textFa: 'نیاز: ۲ نشان انرژی. ۱− تولید انرژی یک بازیکن؛ ۱ تولید انرژی برای شما.',
    prod: { energy: 1 }, anyProd: { res: 'energy', n: 1 } },
  { id: '161', name: 'Convoy From Europa', nameFa: 'کاروان از اروپا', kind: 'event', cost: 15, tags: ['space'],
    textFa: '۱ اقیانوس بگذارید و ۱ کارت بکشید.', oceans: 1, draw: 1 },
  { id: '162', name: 'Imported GHG', nameFa: 'گاز گلخانه‌ای وارداتی', kind: 'event', cost: 7, tags: ['earth', 'space'],
    textFa: '۱ تولید گرما و ۳ گرما.', prod: { heat: 1 }, gain: { heat: 3 } },
  { id: '163', name: 'Imported Nitrogen', nameFa: 'نیتروژن وارداتی', kind: 'event', cost: 23, tags: ['earth', 'space'],
    textFa: '۱ رتبهٔ زمین‌سازی و ۴ گیاه. ۳ میکروب به کارتی دیگر و ۲ جانور به کارتی دیگر بیفزایید.',
    tr: 1, gain: { plants: 4 }, play: (g) => { g.addToCard('microbe', 3, true); g.addToCard('animal', 2, true); } },
  { id: '164', name: 'Micro-Mills', nameFa: 'آسیاب‌های کوچک', kind: 'automated', cost: 3, tags: [], textFa: '۱ تولید گرما.', prod: { heat: 1 } },
  { id: '165', name: 'Magnetic Field Generators', nameFa: 'مولدهای میدان مغناطیسی', kind: 'automated', cost: 20, tags: ['building'],
    textFa: '۴− تولید انرژی، ۲ تولید گیاه؛ ۳ رتبهٔ زمین‌سازی.', prod: { energy: -4, plants: 2 }, tr: 3 },
  { id: '166', name: 'Shuttles', nameFa: 'شاتل‌ها', kind: 'active', cost: 10, tags: ['space'], vp: 1, req: { oxygen: { min: 5 } },
    textFa: 'نیاز: ۵٪ اکسیژن. ۱− تولید انرژی، ۲ تولید مگاکردیت. کارت‌های فضایی ۲ مگاکردیت ارزان‌تر.',
    prod: { energy: -1, mc: 2 }, discount: (c) => (hasTag(c, 'space') ? 2 : 0) },
  { id: '167', name: 'Import of Advanced GHG', nameFa: 'واردات گاز گلخانه‌ای پیشرفته', kind: 'event', cost: 9, tags: ['earth', 'space'],
    textFa: '۲ تولید گرما.', prod: { heat: 2 } },
  { id: '168', name: 'Windmills', nameFa: 'آسیاب‌های بادی', kind: 'automated', cost: 6, tags: ['power', 'building'], vp: 1,
    req: { oxygen: { min: 7 } }, textFa: 'نیاز: ۷٪ اکسیژن. ۱ تولید انرژی.', prod: { energy: 1 } },
  { id: '169', name: 'Tundra Farming', nameFa: 'کشاورزی توندرا', kind: 'automated', cost: 16, tags: ['plant'], vp: 2,
    req: { temperature: { min: -6 } }, textFa: 'نیاز: دمای ۶− یا گرم‌تر. ۱ تولید گیاه، ۲ تولید مگاکردیت و ۱ گیاه.',
    prod: { plants: 1, mc: 2 }, gain: { plants: 1 } },
  { id: '170', name: 'Aerobraked Ammonia Asteroid', nameFa: 'سیارک آمونیاکی ترمز هوایی', kind: 'event', cost: 26, tags: ['space'],
    textFa: '۳ تولید گرما و ۱ تولید گیاه. ۲ میکروب به کارتی دیگر بیفزایید.',
    prod: { heat: 3, plants: 1 }, addCard: { type: 'microbe', n: 2, other: true } },
  { id: '171', name: 'Magnetic Field Dome', nameFa: 'گنبد میدان مغناطیسی', kind: 'automated', cost: 5, tags: ['building'],
    textFa: '۲− تولید انرژی، ۱ تولید گیاه؛ ۱ رتبهٔ زمین‌سازی.', prod: { energy: -2, plants: 1 }, tr: 1 },
  { id: '172', name: 'Pets', nameFa: 'حیوانات خانگی', kind: 'active', cost: 10, tags: ['earth', 'animal'], resource: 'animal', vp: vpPerRes(2),
    textFa: '۱ جانور به این کارت. هر بار هر کسی شهر بگذارد ۱ جانور به این کارت. جانورها را نمی‌توان از این کارت برداشت. ۱ امتیاز برای هر ۲ جانور.',
    addSelf: 1, keepsResources: true, onTilePlaced: (g, e) => { if (e.kind === 'city') g.addRes(1); } },
  { id: '173', name: 'Protected Habitats', nameFa: 'زیستگاه‌های حفاظت‌شده', kind: 'active', cost: 5, tags: [], ce: true,
    textFa: 'رقیبان نمی‌توانند گیاه، جانور یا میکروب شما را بردارند.', protects: true },
  { id: '174', name: 'Protected Valley', nameFa: 'درهٔ حفاظت‌شده', kind: 'automated', cost: 23, tags: ['plant', 'building'],
    textFa: '۲ تولید مگاکردیت. یک فضای سبز روی ناحیهٔ ویژهٔ اقیانوس بگذارید (بدون قاعدهٔ عادی جای‌گذاری).',
    prod: { mc: 2 }, tiles: [{ kind: 'greenery', rule: 'oceanArea' }] },
  { id: '175', name: 'Satellites', nameFa: 'ماهواره‌ها', kind: 'automated', cost: 10, tags: ['space'], ce: true,
    textFa: '۱ تولید مگاکردیت برای هر نشان فضایی که دارید (این هم).', prodBox: (g) => g.prod('mc', g.tags('space')) },
  { id: '176', name: 'Noctis Farming', nameFa: 'کشاورزی نوکتیس', kind: 'automated', cost: 10, tags: ['plant', 'building'], vp: 1,
    req: { temperature: { min: -20 } }, textFa: 'نیاز: دمای ۲۰− یا گرم‌تر. ۱ تولید مگاکردیت و ۲ گیاه.', prod: { mc: 1 }, gain: { plants: 2 } }
];
