// Reviewed in-repo game registry. Only modules listed here can be seeded/published;
// no uploaded or external code is ever executed.
import { lineThree } from '@bg/game-line-three';
import { sealedBids } from '@bg/game-sealed-bids';
import { uno } from '@bg/game-uno';
import { chess } from '@bg/game-chess';
import { snakesLadders } from '@bg/game-snakes-ladders';
import { ludo } from '@bg/game-ludo';
import { amlak } from '@bg/game-amlak';
import { unmatched } from '@bg/game-unmatched';
import { catan } from '@bg/game-catan';
import { risk } from '@bg/game-risk';
import { ticketToRide } from '@bg/game-ticket-to-ride';
import { backgammon } from '@bg/game-backgammon';
import { checkers } from '@bg/game-checkers';
import { othello } from '@bg/game-othello';
import { quoridor } from '@bg/game-quoridor';
import { onitama } from '@bg/game-onitama';
import { go } from '@bg/game-go';
import { santorini } from '@bg/game-santorini';
import { tak } from '@bg/game-tak';
import { abalone } from '@bg/game-abalone';
import { hive } from '@bg/game-hive';
import { noThanks } from '@bg/game-no-thanks';
import { sixNimmt } from '@bg/game-six-nimmt';
import { loveLetter } from '@bg/game-love-letter';
import { skull } from '@bg/game-skull';
import { coup } from '@bg/game-coup';
import { forSale } from '@bg/game-for-sale';
import { highSociety } from '@bg/game-high-society';
import { sushiGo } from '@bg/game-sushi-go';
import { lostCities } from '@bg/game-lost-cities';
import { theMind } from '@bg/game-the-mind';
import { splendor } from '@bg/game-splendor';
import { azul } from '@bg/game-azul';
import { jaipur } from '@bg/game-jaipur';
import { patchwork } from '@bg/game-patchwork';
import { kingdomino } from '@bg/game-kingdomino';
import { pointSalad } from '@bg/game-point-salad';
import { cockroachPoker } from '@bg/game-cockroach-poker';
import { scout } from '@bg/game-scout';
import { century } from '@bg/game-century';
import { seaSaltPaper } from '@bg/game-sea-salt-paper';
import { hanabi } from '@bg/game-hanabi';
import { camelUp } from '@bg/game-camel-up';
import { machiKoro } from '@bg/game-machi-koro';
import { kingOfTokyo } from '@bg/game-king-of-tokyo';
import type { GameDefinition } from '@bg/game-sdk';

export const gameRegistry: readonly GameDefinition[] = [lineThree, sealedBids, uno, unmatched, catan, chess, snakesLadders, ludo, risk, amlak, ticketToRide, backgammon, checkers, othello, quoridor, onitama, go, santorini, tak, abalone, hive, noThanks, sixNimmt, loveLetter, skull, coup, forSale, highSociety, sushiGo, lostCities, theMind, splendor, azul, jaipur, patchwork, kingdomino, pointSalad, cockroachPoker, scout, century, seaSaltPaper, hanabi, camelUp, machiKoro, kingOfTokyo];
