// GENERATED from the official base-game card list by .tmp-trophy/ark-nova/gen-data.py — do not edit by hand.
// Card stats only (cost, size, icons, conditions, printed rewards, ability keywords). Effects live in src/content/.
import type { AnimalData, SponsorData, ProjectData, ScoringData } from './types.ts';

export const ANIMALS: AnimalData[] = [
  {"id": 401, "name": "Cheetah", "cost": 17, "size": 5, "rock": 0, "water": 0, "std": true, "icons": ["predator", "predator", "africa"], "req": {}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["sprint", 3]]},
  {"id": 402, "name": "Lion", "cost": 16, "size": 4, "rock": 0, "water": 0, "std": true, "icons": ["predator", "africa"], "req": {"predator": 3}, "appeal": 9, "cp": 0, "rep": 0, "ab": [["pack", null]]},
  {"id": 403, "name": "Leopard", "cost": 20, "size": 3, "rock": 1, "water": 0, "std": true, "icons": ["predator", "africa"], "req": {"partner": 1}, "appeal": 7, "cp": 1, "rep": 0, "ab": [["hunter", 4]]},
  {"id": 404, "name": "Caracal", "cost": 9, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["predator", "africa"], "req": {}, "appeal": 4, "cp": 0, "rep": 0, "ab": [["hunter", 2]]},
  {"id": 405, "name": "Fennec Fox", "cost": 8, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["predator", "africa"], "req": {}, "appeal": 3, "cp": 0, "rep": 0, "ab": [["clever", null]]},
  {"id": 406, "name": "Siberian Tiger", "cost": 30, "size": 5, "rock": 0, "water": 0, "std": true, "icons": ["predator", "asia"], "req": {"asia": 3}, "appeal": 10, "cp": 2, "rep": 1, "ab": []},
  {"id": 407, "name": "Sumatran Tiger", "cost": 26, "size": 4, "rock": 0, "water": 2, "std": true, "icons": ["predator", "asia"], "req": {"science": 2}, "appeal": 8, "cp": 2, "rep": 1, "ab": []},
  {"id": 408, "name": "Sloth Bear", "cost": 14, "size": 3, "rock": 0, "water": 0, "std": true, "icons": ["predator", "bear", "asia"], "req": {}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["boost", "association"]]},
  {"id": 409, "name": "Sun Bear", "cost": 16, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["predator", "bear", "asia"], "req": {"partner": 1}, "appeal": 5, "cp": 0, "rep": 0, "ab": [["action", "association"]]},
  {"id": 410, "name": "Yellow-throated Marten", "cost": 7, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["predator", "asia"], "req": {}, "appeal": 3, "cp": 0, "rep": 0, "ab": [["hunter", 1]]},
  {"id": 411, "name": "Grizzly Bear", "cost": 22, "size": 5, "rock": 0, "water": 0, "std": true, "icons": ["predator", "bear", "americas"], "req": {"predator": 2, "animals2": 1}, "appeal": 9, "cp": 0, "rep": 0, "ab": [["inventive", 0], ["fullThroated", null]]},
  {"id": 412, "name": "Jaguar", "cost": 16, "size": 4, "rock": 0, "water": 0, "std": true, "icons": ["predator", "americas"], "req": {"americas": 1}, "appeal": 8, "cp": 0, "rep": 0, "ab": [["hunter", 4]]},
  {"id": 413, "name": "Cougar", "cost": 10, "size": 3, "rock": 1, "water": 0, "std": true, "icons": ["predator", "americas"], "req": {}, "appeal": 5, "cp": 0, "rep": 0, "ab": [["jumping", 3]]},
  {"id": 414, "name": "South American Coati", "cost": 11, "size": 2, "rock": 1, "water": 0, "std": true, "icons": ["predator", "bear", "americas"], "req": {}, "appeal": 4, "cp": 0, "rep": 0, "ab": [["inventive", 1]]},
  {"id": 415, "name": "Raccoon", "cost": 11, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["predator", "bear", "americas"], "req": {}, "appeal": 4, "cp": 0, "rep": 0, "ab": [["boost", "association"]]},
  {"id": 416, "name": "Eurasian Brown Bear", "cost": 20, "size": 5, "rock": 0, "water": 1, "std": true, "icons": ["predator", "bear", "europe"], "req": {"bear": 1, "animals2": 1}, "appeal": 8, "cp": 0, "rep": 0, "ab": [["multiplier", "association"], ["fullThroated", null]]},
  {"id": 417, "name": "Wolf", "cost": 12, "size": 4, "rock": 0, "water": 0, "std": true, "icons": ["predator", "europe"], "req": {}, "appeal": 4, "cp": 0, "rep": 0, "ab": [["pack", null]]},
  {"id": 418, "name": "Eurasian Lynx", "cost": 11, "size": 3, "rock": 0, "water": 0, "std": true, "icons": ["predator", "europe"], "req": {"europe": 2}, "appeal": 2, "cp": 0, "rep": 0, "ab": [["iconic", "europe"]]},
  {"id": 419, "name": "European Badger", "cost": 5, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["predator", "europe"], "req": {}, "appeal": 3, "cp": 0, "rep": 0, "ab": [["boost", "animals"]]},
  {"id": 420, "name": "Stoat", "cost": 4, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["predator", "europe"], "req": {"europe": 1}, "appeal": 3, "cp": 0, "rep": 0, "ab": [["hunter", 1]]},
  {"id": 421, "name": "New Zealand Fur Seal", "cost": 17, "size": 5, "rock": 1, "water": 1, "std": true, "icons": ["predator", "australia"], "req": {"animals2": 1}, "appeal": 8, "cp": 0, "rep": 0, "ab": [["fullThroated", null]]},
  {"id": 422, "name": "Australian Sea Lion", "cost": 18, "size": 4, "rock": 0, "water": 1, "std": true, "icons": ["predator", "australia"], "req": {"partner": 1}, "appeal": 7, "cp": 1, "rep": 0, "ab": [["sunbathing", 3]]},
  {"id": 423, "name": "New Zealand Sea Lion", "cost": 17, "size": 3, "rock": 0, "water": 1, "std": true, "icons": ["predator", "australia"], "req": {}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["pack", null]]},
  {"id": 424, "name": "Australian Dingo", "cost": 13, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["predator", "australia"], "req": {}, "appeal": 3, "cp": 0, "rep": 0, "ab": [["pack", null]]},
  {"id": 425, "name": "Tasmanian Devil", "cost": 11, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["predator", "australia"], "req": {"science": 1}, "appeal": 4, "cp": 0, "rep": 1, "ab": [["pouch", 1]]},
  {"id": 426, "name": "African Bush Elephant", "cost": 36, "size": 5, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "africa", "africa"], "req": {"animals2": 1}, "appeal": 10, "cp": 0, "rep": 1, "ab": [["resistance", null]]},
  {"id": 427, "name": "White Rhinoceros", "cost": 24, "size": 4, "rock": 1, "water": 0, "std": true, "icons": ["herbivore", "africa"], "req": {"science": 1}, "appeal": 9, "cp": 0, "rep": 0, "ab": [["assertion", null]]},
  {"id": 428, "name": "Northern Giraffe", "cost": 16, "size": 3, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "africa"], "req": {}, "appeal": 7, "cp": 0, "rep": 0, "ab": [["boost", "sponsors"]]},
  {"id": 429, "name": "Grevy's Zebra", "cost": 12, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "africa"], "req": {"africa": 3}, "appeal": 6, "cp": 0, "rep": 1, "ab": [["boost", "sponsors"], ["flock", 2]]},
  {"id": 430, "name": "Pygmy Hippopotamus", "cost": 15, "size": 2, "rock": 0, "water": 1, "std": true, "icons": ["herbivore", "africa"], "req": {"partner": 1}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["action", "sponsors"]]},
  {"id": 431, "name": "Asian Elephant", "cost": 33, "size": 5, "rock": 0, "water": 1, "std": true, "icons": ["herbivore", "asia", "asia"], "req": {"animals2": 1}, "appeal": 8, "cp": 1, "rep": 0, "ab": [["resistance", null]]},
  {"id": 432, "name": "Indian Rhinoceros", "cost": 25, "size": 4, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "asia"], "req": {"animals2": 1}, "appeal": 9, "cp": 0, "rep": 0, "ab": [["assertion", null]]},
  {"id": 433, "name": "Giant Panda", "cost": 27, "size": 3, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "bear", "asia"], "req": {"herbivore": 1, "bear": 1, "partner": 1}, "appeal": 10, "cp": 2, "rep": 1, "ab": []},
  {"id": 434, "name": "Red Panda", "cost": 16, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "bear", "asia"], "req": {"science": 2}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["multiplier", "sponsors"]]},
  {"id": 435, "name": "Malayan Tapir", "cost": 17, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "asia"], "req": {}, "appeal": 5, "cp": 0, "rep": 1, "ab": [["digging", 3]]},
  {"id": 436, "name": "American Bison", "cost": 18, "size": 5, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "americas", "americas"], "req": {"americas": 3}, "appeal": 4, "cp": 0, "rep": 0, "ab": [["iconic", "americas"]]},
  {"id": 437, "name": "Muskox", "cost": 13, "size": 4, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "americas"], "req": {"americas": 1}, "appeal": 5, "cp": 0, "rep": 0, "ab": [["sponsorMagnet", null]]},
  {"id": 438, "name": "Reindeer", "cost": 12, "size": 3, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "americas"], "req": {}, "appeal": 5, "cp": 0, "rep": 0, "ab": [["flock", 3]]},
  {"id": 439, "name": "Llama", "cost": 10, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "americas"], "req": {}, "appeal": 4, "cp": 0, "rep": 0, "ab": [["flock", 2]]},
  {"id": 440, "name": "Mountain Tapir", "cost": 15, "size": 2, "rock": 1, "water": 0, "std": true, "icons": ["herbivore", "americas"], "req": {}, "appeal": 4, "cp": 1, "rep": 0, "ab": [["digging", 2]]},
  {"id": 441, "name": "European Bison", "cost": 19, "size": 5, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "europe", "europe"], "req": {"partner": 1}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["sponsorMagnet", null]]},
  {"id": 442, "name": "Moose", "cost": 19, "size": 4, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "europe"], "req": {"herbivore": 2}, "appeal": 7, "cp": 0, "rep": 0, "ab": [["multiplier", "sponsors"], ["flock", 4]]},
  {"id": 443, "name": "Red Deer", "cost": 12, "size": 3, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "europe"], "req": {}, "appeal": 5, "cp": 0, "rep": 0, "ab": [["flock", 3]]},
  {"id": 444, "name": "Alpine Ibex", "cost": 10, "size": 2, "rock": 2, "water": 0, "std": true, "icons": ["herbivore", "europe"], "req": {}, "appeal": 5, "cp": 0, "rep": 0, "ab": [["jumping", 2]]},
  {"id": 445, "name": "Crested Porcupine", "cost": 8, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "europe"], "req": {}, "appeal": 3, "cp": 0, "rep": 0, "ab": [["digging", 2]]},
  {"id": 446, "name": "Dugong", "cost": 25, "size": 5, "rock": 0, "water": 2, "std": true, "icons": ["herbivore", "australia", "australia"], "req": {"animals2": 1}, "appeal": 9, "cp": 1, "rep": 0, "ab": [["digging", 4]]},
  {"id": 447, "name": "Red Kangaroo", "cost": 23, "size": 4, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "australia"], "req": {}, "appeal": 7, "cp": 0, "rep": 0, "ab": [["pouch", 2], ["flock", 4]]},
  {"id": 448, "name": "Koala", "cost": 21, "size": 3, "rock": 1, "water": 0, "std": true, "icons": ["herbivore", "bear", "australia"], "req": {"australia": 1}, "appeal": 8, "cp": 0, "rep": 1, "ab": [["pouch", 2]]},
  {"id": 449, "name": "Platypus", "cost": 10, "size": 2, "rock": 0, "water": 1, "std": true, "icons": ["herbivore", "australia"], "req": {}, "appeal": 4, "cp": 0, "rep": 0, "ab": [["venom", 1]]},
  {"id": 450, "name": "Common Wombat", "cost": 9, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["herbivore", "australia"], "req": {}, "appeal": 4, "cp": 0, "rep": 0, "ab": [["pouch", 1]]},
  {"id": 451, "name": "Proboscis Monkey", "cost": 32, "size": 5, "rock": 1, "water": 0, "std": true, "icons": ["primate", "asia"], "req": {"primate": 2, "animals2": 1}, "appeal": 10, "cp": 2, "rep": 0, "ab": [["dominance", null]]},
  {"id": 452, "name": "Senegal Bushbaby", "cost": 10, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["primate", "africa"], "req": {"africa": 2}, "appeal": 1, "cp": 0, "rep": 0, "ab": [["iconic", "africa"]]},
  {"id": 453, "name": "Collared Mangabey", "cost": 20, "size": 4, "rock": 0, "water": 0, "std": true, "icons": ["primate", "africa"], "req": {"africa": 1}, "appeal": 8, "cp": 0, "rep": 0, "ab": [["action", "cards"]]},
  {"id": 454, "name": "Ring-tailed Lemur", "cost": 12, "size": 3, "rock": 1, "water": 0, "std": true, "icons": ["primate", "africa"], "req": {}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["sunbathing", 3]]},
  {"id": 455, "name": "Mantled Guereza", "cost": 13, "size": 3, "rock": 0, "water": 0, "std": true, "icons": ["primate", "africa"], "req": {}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["clever", null]]},
  {"id": 456, "name": "Barbary Macaque", "cost": 13, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["primate", "africa"], "req": {"partner": 1}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["pilfering", 1]]},
  {"id": 457, "name": "Mandrill", "cost": 28, "size": 5, "rock": 0, "water": 0, "std": true, "icons": ["primate", "primate", "africa"], "req": {"primate": 3}, "appeal": 9, "cp": 2, "rep": 0, "ab": [["multiplier", "cards"]]},
  {"id": 458, "name": "Japanese Macaque", "cost": 18, "size": 3, "rock": 0, "water": 1, "std": true, "icons": ["primate", "asia"], "req": {"asia": 1}, "appeal": 7, "cp": 0, "rep": 0, "ab": [["pilfering", 2]]},
  {"id": 459, "name": "Red-shanked Douc", "cost": 17, "size": 4, "rock": 0, "water": 0, "std": true, "icons": ["primate", "asia"], "req": {"science": 1}, "appeal": 7, "cp": 0, "rep": 1, "ab": [["inventive", 0]]},
  {"id": 460, "name": "Dusky-leaf Monkey", "cost": 12, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["primate", "asia"], "req": {}, "appeal": 5, "cp": 0, "rep": 0, "ab": [["clever", null]]},
  {"id": 461, "name": "Horsfield's Tarsier", "cost": 14, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["primate", "asia"], "req": {"partner": 1}, "appeal": 3, "cp": 0, "rep": 2, "ab": [["jumping", 4]]},
  {"id": 462, "name": "Northern Plains Gray Langur", "cost": 13, "size": 3, "rock": 1, "water": 0, "std": true, "icons": ["primate", "asia"], "req": {}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["jumping", 3]]},
  {"id": 463, "name": "Panamanian White-faced Capuchin", "cost": 11, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["primate", "americas"], "req": {"partner": 1}, "appeal": 5, "cp": 0, "rep": 0, "ab": [["pilfering", 1]]},
  {"id": 464, "name": "Brown Spider Monkey", "cost": 17, "size": 4, "rock": 0, "water": 0, "std": true, "icons": ["primate", "americas"], "req": {"primate": 1}, "appeal": 6, "cp": 1, "rep": 0, "ab": [["inventive", 0]]},
  {"id": 465, "name": "Golden Lion Tamarin", "cost": 10, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["primate", "americas"], "req": {}, "appeal": 4, "cp": 0, "rep": 0, "ab": [["clever", null]]},
  {"id": 466, "name": "Bolivian Red Howler", "cost": 12, "size": 3, "rock": 0, "water": 0, "std": true, "icons": ["primate", "americas"], "req": {}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["boost", "cards"]]},
  {"id": 467, "name": "Ecuadorian Squirrel Monkey", "cost": 12, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["primate", "americas"], "req": {}, "appeal": 5, "cp": 0, "rep": 0, "ab": [["clever", null]]},
  {"id": 468, "name": "Cotton-top Tamarin", "cost": 15, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["primate", "americas"], "req": {"science": 2}, "appeal": 4, "cp": 1, "rep": 1, "ab": []},
  {"id": 469, "name": "Nile Crocodile", "cost": 13, "size": 5, "rock": 0, "water": 1, "std": true, "icons": ["reptile", "africa"], "req": {"reptile": 3}, "appeal": 9, "cp": 0, "rep": 0, "ab": [["snapping", 2]], "sp": {"k": "rh", "n": 3}},
  {"id": 470, "name": "Western Green Mamba", "cost": 13, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["reptile", "africa"], "req": {"africa": 1, "reptile": 1}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["venom", 2]], "sp": {"k": "rh", "n": 1}},
  {"id": 471, "name": "African Spurred Tortoise", "cost": 22, "size": 3, "rock": 0, "water": 0, "std": true, "icons": ["reptile", "africa"], "req": {}, "appeal": 6, "cp": 1, "rep": 0, "ab": [["sunbathing", 3]], "sp": {"k": "rh", "n": 2}},
  {"id": 472, "name": "Rock Monitor", "cost": 12, "size": 2, "rock": 1, "water": 0, "std": true, "icons": ["reptile", "africa"], "req": {}, "appeal": 5, "cp": 0, "rep": 0, "ab": [["sunbathing", 3]], "sp": {"k": "rh", "n": 1}},
  {"id": 473, "name": "Common Agama", "cost": 9, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["reptile", "africa"], "req": {}, "appeal": 3, "cp": 0, "rep": 0, "ab": [["sunbathing", 2]], "sp": {"k": "rh", "n": 0}},
  {"id": 474, "name": "Indian Rock Python", "cost": 14, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["reptile", "asia"], "req": {"reptile": 2}, "appeal": 7, "cp": 0, "rep": 0, "ab": [["constriction", null]], "sp": {"k": "rh", "n": 1}},
  {"id": 475, "name": "Indian Cobra", "cost": 13, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["reptile", "asia"], "req": {"science": 2, "animals2": 1}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["hypnosis", 3]], "sp": {"k": "rh", "n": 1}},
  {"id": 476, "name": "Komodo Dragon", "cost": 14, "size": 3, "rock": 0, "water": 0, "std": true, "icons": ["reptile", "asia"], "req": {"asia": 2}, "appeal": 2, "cp": 0, "rep": 0, "ab": [["iconic", "asia"]], "sp": {"k": "rh", "n": 2}},
  {"id": 477, "name": "Veiled Chameleon", "cost": 14, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["reptile", "asia"], "req": {}, "appeal": 4, "cp": 0, "rep": 0, "ab": [["snapping", 1]], "sp": {"k": "rh", "n": 0}},
  {"id": 478, "name": "Chinese Water Dragon", "cost": 8, "size": 1, "rock": 0, "water": 1, "std": true, "icons": ["reptile", "asia"], "req": {}, "appeal": 3, "cp": 0, "rep": 0, "ab": [["sunbathing", 2]], "sp": {"k": "rh", "n": 0}},
  {"id": 479, "name": "American Alligator", "cost": 18, "size": 4, "rock": 0, "water": 1, "std": true, "icons": ["reptile", "americas"], "req": {}, "appeal": 7, "cp": 0, "rep": 0, "ab": [["snapping", 1]], "sp": {"k": "rh", "n": 2}},
  {"id": 480, "name": "Broad-snouted Caiman", "cost": 16, "size": 4, "rock": 0, "water": 1, "std": true, "icons": ["reptile", "americas"], "req": {}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["snapping", 1]], "sp": {"k": "rh", "n": 2}},
  {"id": 481, "name": "Galapagos Giant Tortoise", "cost": 30, "size": 3, "rock": 0, "water": 0, "std": true, "icons": ["reptile", "americas"], "req": {"americas": 2, "animals2": 1}, "appeal": 8, "cp": 2, "rep": 1, "ab": [["sunbathing", 4]], "sp": {"k": "rh", "n": 2}},
  {"id": 482, "name": "Anaconda", "cost": 13, "size": 2, "rock": 0, "water": 1, "std": true, "icons": ["reptile", "americas"], "req": {"partner": 1}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["constriction", null]], "sp": {"k": "rh", "n": 1}},
  {"id": 483, "name": "Boa Constrictor", "cost": 16, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["reptile", "americas"], "req": {"science": 2}, "appeal": 7, "cp": 0, "rep": 0, "ab": [["constriction", null]], "sp": {"k": "rh", "n": 1}},
  {"id": 484, "name": "European Pond Turtle", "cost": 9, "size": 1, "rock": 0, "water": 1, "std": true, "icons": ["reptile", "europe"], "req": {}, "appeal": 4, "cp": 0, "rep": 0, "ab": [], "sp": {"k": "rh", "n": 1}},
  {"id": 485, "name": "Common European Adder", "cost": 10, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["reptile", "europe"], "req": {"partner": 1}, "appeal": 2, "cp": 0, "rep": 0, "ab": [["hypnosis", 3]], "sp": {"k": "rh", "n": 0}},
  {"id": 486, "name": "Common Wall Lizard", "cost": 4, "size": 1, "rock": 1, "water": 0, "std": true, "icons": ["reptile", "europe"], "req": {}, "appeal": 2, "cp": 0, "rep": 0, "ab": [], "sp": {"k": "rh", "n": 0}},
  {"id": 487, "name": "European Grass Snake", "cost": 8, "size": 1, "rock": 0, "water": 1, "std": true, "icons": ["reptile", "europe"], "req": {}, "appeal": 3, "cp": 0, "rep": 0, "ab": [["clever", null]], "sp": {"k": "rh", "n": 0}},
  {"id": 488, "name": "Slow Worm", "cost": 4, "size": 1, "rock": 0, "water": 1, "std": true, "icons": ["reptile", "europe"], "req": {}, "appeal": 2, "cp": 0, "rep": 0, "ab": [], "sp": {"k": "rh", "n": 0}},
  {"id": 489, "name": "Saltwater Crocodile", "cost": 23, "size": 5, "rock": 0, "water": 1, "std": true, "icons": ["reptile", "reptile", "australia"], "req": {"partner": 1}, "appeal": 9, "cp": 0, "rep": 0, "ab": [["snapping", 2]], "sp": {"k": "rh", "n": 3}},
  {"id": 490, "name": "Gould's Monitor", "cost": 15, "size": 3, "rock": 0, "water": 0, "std": true, "icons": ["reptile", "australia"], "req": {}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["scavenging", 2]], "sp": {"k": "rh", "n": 2}},
  {"id": 491, "name": "Frilled Lizard", "cost": 12, "size": 2, "rock": 1, "water": 0, "std": true, "icons": ["reptile", "australia"], "req": {}, "appeal": 5, "cp": 0, "rep": 0, "ab": [["sprint", 1]], "sp": {"k": "rh", "n": 1}},
  {"id": 492, "name": "Inland Taipan", "cost": 10, "size": 2, "rock": 1, "water": 0, "std": true, "icons": ["reptile", "australia"], "req": {"australia": 1, "science": 1}, "appeal": 5, "cp": 0, "rep": 0, "ab": [["venom", 2]], "sp": {"k": "rh", "n": 1}},
  {"id": 493, "name": "Thorny Devil", "cost": 6, "size": 1, "rock": 1, "water": 0, "std": true, "icons": ["reptile", "australia"], "req": {}, "appeal": 3, "cp": 0, "rep": 0, "ab": [], "sp": {"k": "rh", "n": 0}},
  {"id": 494, "name": "African Ostrich", "cost": 20, "size": 5, "rock": 0, "water": 0, "std": true, "icons": ["bird", "africa"], "req": {}, "appeal": 8, "cp": 0, "rep": 0, "ab": [["sprint", 2]], "sp": {"k": "ba", "n": 4}},
  {"id": 495, "name": "Secretary Bird", "cost": 14, "size": 4, "rock": 0, "water": 0, "std": true, "icons": ["bird", "africa"], "req": {}, "appeal": 4, "cp": 1, "rep": 0, "ab": [], "sp": {"k": "ba", "n": 1}},
  {"id": 496, "name": "Marabou", "cost": 10, "size": 3, "rock": 0, "water": 0, "std": true, "icons": ["bird", "africa"], "req": {}, "appeal": 4, "cp": 0, "rep": 0, "ab": [["scavenging", 2]], "sp": {"k": "ba", "n": 1}},
  {"id": 497, "name": "Lesser Flamingo", "cost": 15, "size": 2, "rock": 0, "water": 1, "std": true, "icons": ["bird", "africa"], "req": {}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["posturing", 1]]},
  {"id": 498, "name": "Shoebill", "cost": 9, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["bird", "africa"], "req": {"science": 2}, "appeal": 3, "cp": 1, "rep": 0, "ab": [], "sp": {"k": "ba", "n": 1}},
  {"id": 499, "name": "Cinereous Vulture", "cost": 16, "size": 5, "rock": 0, "water": 0, "std": true, "icons": ["bird", "asia"], "req": {}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["scavenging", 3]], "sp": {"k": "ba", "n": 1}},
  {"id": 500, "name": "Long-billed Vulture", "cost": 20, "size": 4, "rock": 1, "water": 0, "std": true, "icons": ["bird", "asia"], "req": {"science": 1}, "appeal": 5, "cp": 1, "rep": 1, "ab": [["scavenging", 3]], "sp": {"k": "ba", "n": 1}},
  {"id": 501, "name": "Indian Peafowl", "cost": 18, "size": 3, "rock": 0, "water": 0, "std": true, "icons": ["bird", "asia"], "req": {"asia": 1}, "appeal": 7, "cp": 0, "rep": 0, "ab": [["posturing", 2]]},
  {"id": 502, "name": "Great Hornbill", "cost": 13, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["bird", "asia"], "req": {}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["boost", "build"]]},
  {"id": 503, "name": "Snowy Owl", "cost": 11, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["bird", "asia"], "req": {"bird": 2}, "appeal": 4, "cp": 0, "rep": 1, "ab": [["perception", 4]]},
  {"id": 504, "name": "Andean Condor", "cost": 17, "size": 5, "rock": 1, "water": 0, "std": true, "icons": ["bird", "americas"], "req": {"bird": 1}, "appeal": 7, "cp": 0, "rep": 1, "ab": [["scavenging", 4]], "sp": {"k": "ba", "n": 1}},
  {"id": 505, "name": "Bald Eagle", "cost": 23, "size": 4, "rock": 0, "water": 1, "std": true, "icons": ["bird", "americas"], "req": {"animals2": 1}, "appeal": 8, "cp": 0, "rep": 0, "ab": [["determination", null]], "sp": {"k": "ba", "n": 1}},
  {"id": 506, "name": "King Vulture", "cost": 12, "size": 3, "rock": 0, "water": 0, "std": true, "icons": ["bird", "americas"], "req": {"bird": 3}, "appeal": 9, "cp": 0, "rep": 0, "ab": [["scavenging", 5]], "sp": {"k": "ba", "n": 1}},
  {"id": 507, "name": "Greater Rhea", "cost": 12, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["bird", "americas"], "req": {}, "appeal": 5, "cp": 0, "rep": 0, "ab": [["sprint", 1]]},
  {"id": 508, "name": "Scarlet Macaw", "cost": 16, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["bird", "americas"], "req": {"partner": 1}, "appeal": 4, "cp": 0, "rep": 0, "ab": [["posturing", 3]]},
  {"id": 509, "name": "Golden Eagle", "cost": 20, "size": 5, "rock": 1, "water": 0, "std": true, "icons": ["bird", "europe"], "req": {"animals2": 1}, "appeal": 7, "cp": 0, "rep": 0, "ab": [["determination", null]], "sp": {"k": "ba", "n": 1}},
  {"id": 510, "name": "White Stork", "cost": 9, "size": 4, "rock": 0, "water": 0, "std": true, "icons": ["bird", "europe"], "req": {"europe": 1}, "appeal": 4, "cp": 0, "rep": 0, "ab": [["multiplier", "build"]], "sp": {"k": "ba", "n": 1}},
  {"id": 511, "name": "Greater Flamingo", "cost": 16, "size": 3, "rock": 0, "water": 1, "std": true, "icons": ["bird", "europe"], "req": {}, "appeal": 7, "cp": 0, "rep": 0, "ab": [["posturing", 1]]},
  {"id": 512, "name": "Eurasian Eagle-owl", "cost": 10, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["bird", "europe"], "req": {"partner": 1}, "appeal": 4, "cp": 0, "rep": 0, "ab": [["perception", 4]]},
  {"id": 513, "name": "Barn Owl", "cost": 12, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["bird", "europe"], "req": {}, "appeal": 3, "cp": 0, "rep": 0, "ab": [["perception", 4]]},
  {"id": 514, "name": "Emu", "cost": 22, "size": 5, "rock": 0, "water": 0, "std": true, "icons": ["bird", "australia"], "req": {"australia": 2}, "appeal": 7, "cp": 0, "rep": 0, "ab": [["peacocking", null]]},
  {"id": 515, "name": "Australian Pelican", "cost": 13, "size": 4, "rock": 0, "water": 2, "std": true, "icons": ["bird", "australia"], "req": {}, "appeal": 5, "cp": 0, "rep": 0, "ab": [["action", "build"]]},
  {"id": 516, "name": "Northern Cassowary", "cost": 12, "size": 3, "rock": 0, "water": 0, "std": true, "icons": ["bird", "australia"], "req": {"partner": 1}, "appeal": 6, "cp": 0, "rep": 0, "ab": [["multiplier", "build"]]},
  {"id": 517, "name": "Laughing Kookaburra", "cost": 9, "size": 2, "rock": 0, "water": 0, "std": true, "icons": ["bird", "australia"], "req": {"australia": 1}, "appeal": 0, "cp": 0, "rep": 0, "ab": [["iconic", "australia"]]},
  {"id": 518, "name": "Lesser Bird-of-paradise", "cost": 15, "size": 1, "rock": 0, "water": 0, "std": true, "icons": ["bird", "australia"], "req": {}, "appeal": 5, "cp": 0, "rep": 0, "ab": [["posturing", 1]]},
  {"id": 519, "name": "(domestic) Goat", "cost": 7, "size": 0, "rock": 0, "water": 0, "std": false, "icons": ["pet"], "req": {}, "appeal": 0, "cp": 0, "rep": 0, "ab": [["pettingZoo", null]], "sp": {"k": "pz", "n": 1}},
  {"id": 520, "name": "Sheep", "cost": 7, "size": 0, "rock": 0, "water": 0, "std": false, "icons": ["pet"], "req": {}, "appeal": 0, "cp": 0, "rep": 0, "ab": [["pettingZoo", null]], "sp": {"k": "pz", "n": 1}},
  {"id": 521, "name": "Horse", "cost": 7, "size": 0, "rock": 0, "water": 0, "std": false, "icons": ["pet"], "req": {}, "appeal": 0, "cp": 0, "rep": 1, "ab": [["pettingZoo", null]], "sp": {"k": "pz", "n": 1}},
  {"id": 522, "name": "Donkey", "cost": 7, "size": 0, "rock": 0, "water": 0, "std": false, "icons": ["pet"], "req": {}, "appeal": 0, "cp": 0, "rep": 0, "ab": [["pettingZoo", null], ["inventive", 1]], "sp": {"k": "pz", "n": 1}},
  {"id": 523, "name": "Domestic Rabbit", "cost": 7, "size": 0, "rock": 0, "water": 0, "std": false, "icons": ["pet"], "req": {}, "appeal": 0, "cp": 0, "rep": 0, "ab": [["pettingZoo", null]], "sp": {"k": "pz", "n": 1}},
  {"id": 524, "name": "Mangalica", "cost": 7, "size": 0, "rock": 0, "water": 0, "std": false, "icons": ["pet"], "req": {}, "appeal": 0, "cp": 0, "rep": 0, "ab": [["pettingZoo", null], ["digging", 1]], "sp": {"k": "pz", "n": 1}},
  {"id": 525, "name": "Guinea Pig", "cost": 7, "size": 0, "rock": 0, "water": 0, "std": false, "icons": ["pet"], "req": {}, "appeal": 0, "cp": 0, "rep": 0, "ab": [["pettingZoo", null]], "sp": {"k": "pz", "n": 1}},
  {"id": 526, "name": "Alpaca", "cost": 7, "size": 0, "rock": 0, "water": 0, "std": false, "icons": ["pet"], "req": {}, "appeal": 0, "cp": 0, "rep": 0, "ab": [["pettingZoo", null]], "sp": {"k": "pz", "n": 1}},
  {"id": 527, "name": "Coconut Lorikeet", "cost": 7, "size": 0, "rock": 0, "water": 0, "std": false, "icons": ["pet"], "req": {}, "appeal": 0, "cp": 0, "rep": 0, "ab": [["pettingZoo", null]], "sp": {"k": "pz", "n": 1}},
  {"id": 528, "name": "Bennett's Wallaby", "cost": 7, "size": 0, "rock": 0, "water": 0, "std": false, "icons": ["pet"], "req": {}, "appeal": 0, "cp": 0, "rep": 0, "ab": [["pettingZoo", null], ["pouch", 1]], "sp": {"k": "pz", "n": 1}}
];

export const SPONSORS: SponsorData[] = [
  {"id": 201, "name": "Science Lab", "level": 5, "rock": 0, "water": 0, "icons": ["science"], "req": {"sponsors2": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 202, "name": "Spokesperson", "level": 5, "rock": 0, "water": 0, "icons": ["science"], "req": {"science": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 203, "name": "Veterinarian", "level": 4, "rock": 0, "water": 0, "icons": ["science"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 204, "name": "Science Museum", "level": 4, "rock": 0, "water": 0, "icons": ["science"], "req": {"science": 4}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 205, "name": "Gorilla Field Research", "level": 3, "rock": 0, "water": 0, "icons": ["science"], "req": {"science": 3}, "appeal": 0, "cp": 1, "rep": 2},
  {"id": 206, "name": "Medical Breakthrough", "level": 5, "rock": 0, "water": 0, "icons": ["science"], "req": {"science": 4}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 207, "name": "Basic Research", "level": 4, "rock": 0, "water": 0, "icons": ["science"], "req": {"sponsors2": 1, "appeal25": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 208, "name": "Science Library", "level": 4, "rock": 0, "water": 0, "icons": ["science"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 209, "name": "Technology Institute", "level": 5, "rock": 0, "water": 0, "icons": ["science"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 210, "name": "Expert On The Americas", "level": 4, "rock": 0, "water": 0, "icons": ["americas"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 211, "name": "Expert On Europe", "level": 5, "rock": 0, "water": 0, "icons": ["europe"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 212, "name": "Expert On Australia", "level": 5, "rock": 0, "water": 0, "icons": ["australia"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 213, "name": "Expert On Asia", "level": 5, "rock": 0, "water": 0, "icons": ["asia"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 214, "name": "Expert On Africa", "level": 4, "rock": 0, "water": 0, "icons": ["africa"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 215, "name": "Breeding Cooperation", "level": 4, "rock": 0, "water": 0, "icons": [], "req": {"partner": 2}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 216, "name": "Talented Communicator", "level": 5, "rock": 0, "water": 0, "icons": [], "req": {"sponsors2": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 217, "name": "Engineer", "level": 4, "rock": 0, "water": 0, "icons": [], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 218, "name": "Breeding Program", "level": 4, "rock": 0, "water": 0, "icons": [], "req": {"science": 2}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 219, "name": "Diversity Researcher", "level": 5, "rock": 0, "water": 0, "icons": ["science"], "req": {"sponsors2": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 220, "name": "Federal Grants", "level": 4, "rock": 0, "water": 0, "icons": ["science"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 221, "name": "Archaeologist", "level": 4, "rock": 0, "water": 0, "icons": ["science"], "req": {"science": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 222, "name": "Release Of Patents", "level": 5, "rock": 0, "water": 0, "icons": [], "req": {"appeal25": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 223, "name": "Science Institute", "level": 3, "rock": 0, "water": 0, "icons": ["science", "science"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 224, "name": "Migration Recording", "level": 4, "rock": 0, "water": 0, "icons": ["science"], "req": {"science": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 225, "name": "Quarantine Lab", "level": 3, "rock": 0, "water": 0, "icons": ["science"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 226, "name": "Foreign Institute", "level": 6, "rock": 0, "water": 0, "icons": ["science"], "req": {}, "appeal": 0, "cp": 0, "rep": 2},
  {"id": 227, "name": "Waza Special Assignment", "level": 6, "rock": 0, "water": 0, "icons": [], "req": {"rep": 6}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 228, "name": "Waza Small Animal Program", "level": 5, "rock": 0, "water": 0, "icons": [], "req": {"rep": 3}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 229, "name": "Expert In Small Animals", "level": 5, "rock": 0, "water": 0, "icons": [], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 230, "name": "Expert In Large Animals", "level": 4, "rock": 0, "water": 0, "icons": [], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 231, "name": "Sponsorship: Primates", "level": 3, "rock": 0, "water": 0, "icons": [], "req": {"primate": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 232, "name": "Sponsorship: Reptiles", "level": 3, "rock": 0, "water": 0, "icons": [], "req": {"reptile": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 233, "name": "Sponsorship: Vultures", "level": 3, "rock": 0, "water": 0, "icons": [], "req": {"bird": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 234, "name": "Sponsorship: Lions", "level": 3, "rock": 0, "water": 0, "icons": [], "req": {"predator": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 235, "name": "Sponsorship: Elephants", "level": 3, "rock": 0, "water": 0, "icons": [], "req": {"herbivore": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 236, "name": "Primatologist", "level": 4, "rock": 0, "water": 0, "icons": ["primate"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 237, "name": "Herpetologist", "level": 4, "rock": 0, "water": 0, "icons": ["reptile"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 238, "name": "Ornithologist", "level": 4, "rock": 0, "water": 0, "icons": ["bird"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 239, "name": "Expert In Predators", "level": 4, "rock": 0, "water": 0, "icons": ["predator"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 240, "name": "Expert In Herbivores", "level": 4, "rock": 0, "water": 0, "icons": ["herbivore"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 241, "name": "Hydrologist", "level": 5, "rock": 0, "water": 1, "icons": [], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 242, "name": "Geologist", "level": 5, "rock": 1, "water": 0, "icons": [], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 243, "name": "Meerkat Den", "level": 5, "rock": 1, "water": 0, "icons": ["herbivore"], "req": {"rep": 3}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 244, "name": "Penguin Pool", "level": 5, "rock": 0, "water": 1, "icons": ["bird"], "req": {"rep": 3}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 245, "name": "Aquarium", "level": 5, "rock": 0, "water": 2, "icons": [], "req": {"rep": 3}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 246, "name": "Cable Car", "level": 6, "rock": 2, "water": 0, "icons": [], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 247, "name": "Baboon Rock", "level": 6, "rock": 1, "water": 0, "icons": ["primate"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 248, "name": "Rhesus Monkey Park", "level": 5, "rock": 0, "water": 0, "icons": ["primate"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 249, "name": "Barred Owl Hut", "level": 6, "rock": 0, "water": 0, "icons": ["bird"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 250, "name": "Sea Turtle Tank", "level": 5, "rock": 0, "water": 1, "icons": ["reptile"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 251, "name": "Polar Bear Exhibit", "level": 5, "rock": 0, "water": 1, "icons": ["predator", "bear"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 252, "name": "Spotted Hyena Compound", "level": 5, "rock": 1, "water": 0, "icons": ["predator"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 253, "name": "Okapi Stable", "level": 6, "rock": 0, "water": 0, "icons": ["herbivore"], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 254, "name": "Zoo School", "level": 5, "rock": 0, "water": 0, "icons": [], "req": {}, "appeal": 0, "cp": 1, "rep": 1},
  {"id": 255, "name": "Adventure Playground", "level": 3, "rock": 1, "water": 0, "icons": [], "req": {}, "appeal": 4, "cp": 0, "rep": 0},
  {"id": 256, "name": "Water Playground", "level": 3, "rock": 0, "water": 1, "icons": [], "req": {}, "appeal": 4, "cp": 0, "rep": 0},
  {"id": 257, "name": "Side Entrance", "level": 3, "rock": 0, "water": 0, "icons": [], "req": {}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 258, "name": "Native Seabirds", "level": 5, "rock": 0, "water": 0, "icons": ["bird"], "req": {"appeal25": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 259, "name": "Native Lizards", "level": 5, "rock": 0, "water": 0, "icons": ["reptile"], "req": {"appeal25": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 260, "name": "Native Farm Animals", "level": 5, "rock": 0, "water": 0, "icons": ["herbivore"], "req": {"appeal25": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 261, "name": "Guided School Tours", "level": 3, "rock": 0, "water": 0, "icons": [], "req": {}, "appeal": 1, "cp": 1, "rep": 0},
  {"id": 262, "name": "Explorer", "level": 5, "rock": 0, "water": 0, "icons": [], "req": {"sponsors2": 1}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 263, "name": "Waza Large Animal Program", "level": 5, "rock": 0, "water": 0, "icons": [], "req": {"sponsors2": 1, "rep": 6}, "appeal": 0, "cp": 0, "rep": 0},
  {"id": 264, "name": "Free-range New World Monkeys", "level": 5, "rock": 0, "water": 0, "icons": ["primate"], "req": {"appeal25": 1}, "appeal": 0, "cp": 0, "rep": 0}
];

export const PROJECTS: ProjectData[] = [
  {"id": 101, "name": "Species Diversity", "base": true, "kind": "icons", "icon": "categories", "slots": [{"cp": 5, "rep": 0, "need": 5}, {"cp": 3, "rep": 0, "need": 4}, {"cp": 2, "rep": 0, "need": 3}]},
  {"id": 102, "name": "Habitat Diversity", "base": true, "kind": "icons", "icon": "continents", "slots": [{"cp": 5, "rep": 0, "need": 5}, {"cp": 3, "rep": 0, "need": 4}, {"cp": 2, "rep": 0, "need": 3}]},
  {"id": 103, "name": "Africa", "base": true, "kind": "icons", "icon": "africa", "slots": [{"cp": 5, "rep": 0, "need": 5}, {"cp": 3, "rep": 0, "need": 4}, {"cp": 2, "rep": 0, "need": 2}]},
  {"id": 104, "name": "Americas", "base": true, "kind": "icons", "icon": "americas", "slots": [{"cp": 5, "rep": 0, "need": 5}, {"cp": 3, "rep": 0, "need": 4}, {"cp": 2, "rep": 0, "need": 2}]},
  {"id": 105, "name": "Australia", "base": true, "kind": "icons", "icon": "australia", "slots": [{"cp": 5, "rep": 0, "need": 5}, {"cp": 4, "rep": 0, "need": 4}, {"cp": 2, "rep": 0, "need": 2}]},
  {"id": 106, "name": "Asia", "base": true, "kind": "icons", "icon": "asia", "slots": [{"cp": 5, "rep": 0, "need": 5}, {"cp": 3, "rep": 0, "need": 4}, {"cp": 2, "rep": 0, "need": 2}]},
  {"id": 107, "name": "Europe", "base": true, "kind": "icons", "icon": "europe", "slots": [{"cp": 5, "rep": 0, "need": 5}, {"cp": 4, "rep": 0, "need": 4}, {"cp": 2, "rep": 0, "need": 2}]},
  {"id": 108, "name": "Primates", "base": true, "kind": "icons", "icon": "primate", "slots": [{"cp": 5, "rep": 0, "need": 5}, {"cp": 4, "rep": 0, "need": 4}, {"cp": 2, "rep": 0, "need": 2}]},
  {"id": 109, "name": "Reptiles", "base": true, "kind": "icons", "icon": "reptile", "slots": [{"cp": 5, "rep": 0, "need": 5}, {"cp": 4, "rep": 0, "need": 4}, {"cp": 2, "rep": 0, "need": 2}]},
  {"id": 110, "name": "Predators", "base": true, "kind": "icons", "icon": "predator", "slots": [{"cp": 5, "rep": 0, "need": 5}, {"cp": 4, "rep": 0, "need": 4}, {"cp": 2, "rep": 0, "need": 2}]},
  {"id": 111, "name": "Herbivores", "base": true, "kind": "icons", "icon": "herbivore", "slots": [{"cp": 5, "rep": 0, "need": 5}, {"cp": 4, "rep": 0, "need": 4}, {"cp": 2, "rep": 0, "need": 2}]},
  {"id": 112, "name": "Birds", "base": true, "kind": "icons", "icon": "bird", "slots": [{"cp": 5, "rep": 0, "need": 5}, {"cp": 4, "rep": 0, "need": 4}, {"cp": 2, "rep": 0, "need": 2}]},
  {"id": 113, "name": "Bavarian Forest national park", "base": false, "kind": "release", "icon": "europe", "slots": [{"cp": 5, "rep": 0, "size": 4}, {"cp": 4, "rep": 0, "size": 3}, {"cp": 3, "rep": 0, "size": 2}], "played": {"rep": 1}},
  {"id": 114, "name": "Yosemite national park", "base": false, "kind": "release", "icon": "americas", "slots": [{"cp": 5, "rep": 0, "size": 4}, {"cp": 4, "rep": 0, "size": 3}, {"cp": 3, "rep": 0, "size": 2}], "played": {"rep": 1}},
  {"id": 115, "name": "Angthong national park", "base": false, "kind": "release", "icon": "asia", "slots": [{"cp": 5, "rep": 0, "size": 4}, {"cp": 4, "rep": 0, "size": 3}, {"cp": 3, "rep": 0, "size": 2}], "played": {"rep": 1}},
  {"id": 116, "name": "Serengeti national park", "base": false, "kind": "release", "icon": "africa", "slots": [{"cp": 5, "rep": 0, "size": 4}, {"cp": 4, "rep": 0, "size": 3}, {"cp": 3, "rep": 0, "size": 2}], "played": {"rep": 1}},
  {"id": 117, "name": "Blue mountains national park", "base": false, "kind": "release", "icon": "australia", "slots": [{"cp": 5, "rep": 0, "size": 4}, {"cp": 4, "rep": 0, "size": 3}, {"cp": 3, "rep": 0, "size": 2}], "played": {"rep": 1}},
  {"id": 118, "name": "Savanna", "base": false, "kind": "release", "icon": "predator", "slots": [{"cp": 5, "rep": 0, "size": 4}, {"cp": 4, "rep": 0, "size": 3}, {"cp": 3, "rep": 0, "size": 2}], "played": {"rep": 1}},
  {"id": 119, "name": "Low Mountain Range", "base": false, "kind": "release", "icon": "bird", "slots": [{"cp": 5, "rep": 0, "size": 4}, {"cp": 4, "rep": 0, "size": 3}, {"cp": 3, "rep": 0, "size": 2}], "played": {"rep": 1}},
  {"id": 120, "name": "Bamboo Forest", "base": false, "kind": "release", "icon": "herbivore", "slots": [{"cp": 5, "rep": 0, "size": 4}, {"cp": 4, "rep": 0, "size": 3}, {"cp": 3, "rep": 0, "size": 2}], "played": {"rep": 1}},
  {"id": 121, "name": "Sea Cave", "base": false, "kind": "release", "icon": "reptile", "slots": [{"cp": 5, "rep": 0, "size": 4}, {"cp": 4, "rep": 0, "size": 3}, {"cp": 3, "rep": 0, "size": 2}], "played": {"rep": 1}},
  {"id": 122, "name": "Jungle", "base": false, "kind": "release", "icon": "primate", "slots": [{"cp": 5, "rep": 0, "size": 4}, {"cp": 4, "rep": 0, "size": 3}, {"cp": 3, "rep": 0, "size": 2}], "played": {"rep": 1}},
  {"id": 123, "name": "Bird breeding program", "base": false, "kind": "breed", "icon": "bird", "slots": [{"cp": 2, "rep": 2}, {"cp": 1, "rep": 2}, {"cp": 2, "rep": 0}]},
  {"id": 124, "name": "Predator breeding program", "base": false, "kind": "breed", "icon": "predator", "slots": [{"cp": 2, "rep": 2}, {"cp": 1, "rep": 2}, {"cp": 2, "rep": 0}]},
  {"id": 125, "name": "Reptile breeding program", "base": false, "kind": "breed", "icon": "reptile", "slots": [{"cp": 2, "rep": 2}, {"cp": 1, "rep": 2}, {"cp": 2, "rep": 0}]},
  {"id": 126, "name": "Herbivore breeding program", "base": false, "kind": "breed", "icon": "herbivore", "slots": [{"cp": 2, "rep": 2}, {"cp": 1, "rep": 2}, {"cp": 2, "rep": 0}]},
  {"id": 127, "name": "Primate breeding program", "base": false, "kind": "breed", "icon": "primate", "slots": [{"cp": 2, "rep": 2}, {"cp": 1, "rep": 2}, {"cp": 2, "rep": 0}]},
  {"id": 128, "name": "Aquatic", "base": false, "kind": "icons", "icon": "water", "slots": [{"cp": 4, "rep": 0, "need": 5}, {"cp": 3, "rep": 0, "need": 4}, {"cp": 2, "rep": 0, "need": 2}]},
  {"id": 129, "name": "Geological", "base": false, "kind": "icons", "icon": "rock", "slots": [{"cp": 4, "rep": 0, "need": 5}, {"cp": 3, "rep": 0, "need": 3}, {"cp": 2, "rep": 0, "need": 2}]},
  {"id": 130, "name": "Small Animals", "base": false, "kind": "icons", "icon": "small", "slots": [{"cp": 4, "rep": 0, "need": 8}, {"cp": 3, "rep": 0, "need": 5}, {"cp": 2, "rep": 0, "need": 2}]},
  {"id": 131, "name": "Large Animals", "base": false, "kind": "icons", "icon": "large", "slots": [{"cp": 4, "rep": 0, "need": 4}, {"cp": 3, "rep": 0, "need": 3}, {"cp": 2, "rep": 0, "need": 2}]},
  {"id": 132, "name": "Research", "base": false, "kind": "icons", "icon": "science", "slots": [{"cp": 4, "rep": 0, "need": 5}, {"cp": 3, "rep": 0, "need": 4}, {"cp": 2, "rep": 0, "need": 2}]}
];

export const SCORING: ScoringData[] = [
  {"id": 1, "name": "Large Animal Zoo", "table": {"1": 1, "2": 2, "4": 3, "5": 4}},
  {"id": 2, "name": "Small Animal Zoo", "table": {"3": 1, "6": 2, "8": 3, "10": 4}},
  {"id": 3, "name": "Research Zoo", "table": {"3": 1, "4": 2, "5": 3, "6": 4}},
  {"id": 4, "name": "Architectural Zoo", "table": {}},
  {"id": 5, "name": "Conservation Zoo", "table": {"3": 1, "4": 2, "5": 3, "6": 4}},
  {"id": 6, "name": "Naturalists' Zoo", "table": {"6": 1, "12": 2, "18": 3, "24": 4}},
  {"id": 7, "name": "Favorite Zoo", "table": {"6": 1, "9": 2, "12": 3, "15": 4}},
  {"id": 8, "name": "Sponsored Zoo", "table": {"3": 1, "6": 2, "8": 3, "10": 4}},
  {"id": 9, "name": "Diverse species Zoo", "table": {}},
  {"id": 10, "name": "Climbing Park", "table": {"1": 1, "3": 2, "5": 3, "7": 4}},
  {"id": 11, "name": "Aquatic Park", "table": {"2": 1, "4": 2, "6": 3, "8": 4}}
];
